### ISSUE TITLE
All Blinks fall asleep at the same time

### ISSUE THREAD

**Issue by jbobrow** [Move38/Blinks-SDK#39]
Every time a Blink's button is pressed, let contiguous Blinks know a game action has occurred and reset the sleep timer. This way all Blinks will fall asleep at roughly the same time.

**Comment by kenj1** [comment]
I like this but would add (to preserve battery life):  
Allow the user to simultaneously force sleep all contiguous blinks (user initiated "shutoff" instead of requiring a 10 minute wasted battery timeout cycle anytime someone uses a Blink.    For example, a 10 second long press puts the Blink (and all contiguous Blinks) into sleep mode.

Btw, I've made use of the forced sleep method already (buried in the core) when I implemented a "menu mode" for the game.

**Comment by jbobrow** [comment]
Spot on @kenj1. I'd love to try out your menu mode, we've implemented a couple and think we have a good one for distribution. It's great that you've made one already, where should I look for it?!

Also, this is the spec for our menu: [here](https://github.com/Move38/Move38-Arduino-Platform/issues/41#issue-363757177)

**Comment by kenj1** [comment]
I was using it similar to what you're doing with your menu (although I don't have a programmer mode yet). In addition to sleep, my menu was used to also send a "reset" to the connected blinks so they'd return to game start.

**Comment by jbobrow** [comment]
@bigjosh The milestones/issues are not particularly suited to the way we are using GitHub. i.e. your repo can only have milestones created by you. I created one here and listed the issues that are not synched with this repo, so the issues aren't tied to the milestone. Either way, I think the list and order still make sense, feel free to copy them into a local milestone and/or make it into 4 milestones for each issue group :)

**Comment by jbobrow** [comment]
This is all functioning great now :) Blinks are kept awake by the last clicked Blink (this virally spreads) and they all fall asleep at the same timeout or if forced to sleep.
