### ISSUE TITLE
Not sure why compile sizes differ on MacOS and Windows

### ISSUE THREAD

**Issue by jbobrow** [Move38/Blinks-SDK#78]
Are there dependencies that are different on a mac vs pc? Seems odd that some of our games in development can compile and upload from a pc but not from our macs. Would love to solve this so that we can be consistent about game size.

**Comment by jbobrow** [comment]
A great example right now is the game Pay Up. The team developing this game has it up and running great on their devices, but when we pull the master, it is too large for ours.

**Comment by bigjosh** [comment]
It is likely due to different versions of the `avr-gcc` compiler in the different Arduino versions.  

First make sure both systems are using the same downloaded version of the Arduino IDE. If so, then they *should* be using the same version of the compiler... but not always.  If they are not running the same version of the IDE, download the latest IDE version on both systems and see if the output size matches.  If not then we need to check what version compiler each is using.

To find out what version of the compiler is running on each system, find out where your `avr-gcc` executable is by turning on `verbose output` in preferences...

![image](https://user-images.githubusercontent.com/5520281/76564619-4a655300-647f-11ea-8f73-589d2f99cb1c.png)

...and then compile a sketch. Now look in the console window for a line that runs `avr-gcc`. Here is a line from my machine with the `avr-gcc` call highlighted...

![image](https://user-images.githubusercontent.com/5520281/76564971-03c42880-6480-11ea-987c-2b40d72e4cfe.png)


Now open a command window in that directory and run `avr-gcc` with the `--version` (two dashes) argument. This is what it looks like on my windows machine...

![image](https://user-images.githubusercontent.com/5520281/76565172-6ae1dd00-6480-11ea-8393-20c5f46085a6.png)

So I am apparently running running 4.3.2.

I also just checked and the version that is included with the most recent Windows version 1.8.12 of the IDE is 7.3.0. 

Report back what you find on your machines!

**Comment by ReluctantPirate** [comment]
![Screen Shot 2020-03-12 at 5 18 34 PM](https://user-images.githubusercontent.com/10680196/76567660-a337ea00-6485-11ea-9278-e6064e06f61b.png)
Here's what I've got running on my machine

**Comment by bigjosh** [comment]
@ReluctantPirate Are you running the latest version 1.8.12 of the Arduino IDE?

**Comment by jbobrow** [comment]
Running Arduino 1.8.9 on MacOS 10.14.6
GCC version 5.4.0
<img width="962" alt="Screen Shot 2020-03-13 at 10 56 59 AM" src="https://user-images.githubusercontent.com/772799/76632328-6fa69f80-6519-11ea-965d-6d177bc59712.png">

**Comment by bigjosh** [comment]
Hmm... According to the [Release Notes](https://www.arduino.cc/en/Main/ReleaseNotes), the last time they updated the `gcc` was to `5.4.0` on 2018.08.23, and yet my Windows install seems to be on `7.3.0`. :/

Hmmm.... I guess I'll dig in on the Arduino stuff.. :/

**Comment by bigjosh** [comment]
There appear to be some issues with which [tools get called by the IDE sometimes](https://github.com/arduino/arduino-cli/issues/60), and also it looks like there are [specific issues with the OSX release](https://www.arduino.cc/en/Main/ReleaseNotes) that make it different that Windows and Linux (although the `gcc` does not seem to be explicitly part of that?). 

Hmmm...

Let's see if we can get the Windows and OSX systems on the same version of the AVR tools using the Boards Manager.

On both systems, go into the Boards Manager and find the `AVR Boards` entry (it is the first one on my dev machine). 

![2020-03-13_12h57_28](https://user-images.githubusercontent.com/5520281/76642970-94efd980-652a-11ea-956b-d8c5d22c466e.png)

Hopefully the current version on the OSX and Windows machines will be _different_. If so, then try to find the most recent version that is available on both machines and set them both to the same version and do `update`. 

Now try again to build the game that was not working on OSX. *Hopefully* at least the results will be the same - even if same is that it does not work on either.

Report back with what you find!

**Comment by jbobrow** [comment]
Looks like 1.8.12 installed brings my gcc version up to 7.3.0.

In my boards manager the version I currently have selected is 1.8.2, looks like you have a newer option of 1.8.5... that doesn't seem to be available on MacOS.

The above are great instructions, we'll check w/ PayUp to ask them to follow these instructions with us.

**Comment by jbobrow** [comment]
Version of GCC is the culprit
